<a href="https://colab.research.google.com/github/Ashin-D/santander-eda-prediction/blob/main/Santander_Data_Preprocessing1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import numpy as np

df = pd.read_csv('/content/train.csv')

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)
df.head()

Dataset loaded successfully!
Dataset shape: (40296, 371)

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0.0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0.0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0.0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0.0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0.0

In [2]:

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes.value_counts())

print("\nFirst five rows:")
display(df.head())

print("\nDataset information:")
df.info()

Number of rows: 40296
Number of columns: 371

Column names:
['ID', 'var3', 'var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1', 'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1', 'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1', 'imp_op_var40_efect_ult3', 'imp_op_var40_ult1', 'imp_op_var41_comer_ult1', 'imp_op_var41_comer_ult3', 'imp_op_var41_efect_ult1', 'imp_op_var41_efect_ult3', 'imp_op_var41_ult1', 'imp_op_var39_efect_ult1', 'imp_op_var39_efect_ult3', 'imp_op_var39_ult1', 'imp_sal_var16_ult1', 'ind_var1_0', 'ind_var1', 'ind_var2_0', 'ind_var2', 'ind_var5_0', 'ind_var5', 'ind_var6_0', 'ind_var6', 'ind_var8_0', 'ind_var8', 'ind_var12_0', 'ind_var12', 'ind_var13_0', 'ind_var13_corto_0', 'ind_var13_corto', 'ind_var13_largo_0', 'ind_var13_largo', 'ind_var13_medio_0', 'ind_var13_medio', 'ind_var13', 'ind_var14_0', 'ind_var14', 'ind_var17_0', 'ind_var17', 'ind_var18_0', 'ind_var18', 'ind_var19', 'ind_var20_0', 'ind_var20', 'ind_var24_0', 'ind_var24', 'ind_var25_cte', 'ind_var26_0', 'ind_var26_cte', 'ind_var26', 'ind_var25_0', 'ind_var25', 'ind_var27_0', 'ind_var28_0', 'ind_var28', 'ind_var27', 'ind_var29_0', 'ind_var29', 'ind_var30_0', 'ind_var30', 'ind_var31_0', 'ind_var31', 'ind_var32_cte', 'ind_var32_0', 'ind_var32', 'ind_var33_0', 'ind_var33', 'ind_var34_0', 'ind_var34', 'ind_var37_cte', 'ind_var37_0', 'ind_var37', 'ind_var39_0', 'ind_var40_0', 'ind_var40', 'ind_var41_0', 'ind_var41', 'ind_var39', 'ind_var44_0', 'ind_var44', 'ind_var46_0', 'ind_var46', 'num_var1_0', 'num_var1', 'num_var4', 'num_var5_0', 'num_var5', 'num_var6_0', 'num_var6', 'num_var8_0', 'num_var8', 'num_var12_0', 'num_var12', 'num_var13_0', 'num_var13_corto_0', 'num_var13_corto', 'num_var13_largo_0', 'num_var13_largo', 'num_var13_medio_0', 'num_var13_medio', 'num_var13', 'num_var14_0', 'num_var14', 'num_var17_0', 'num_var17', 'num_var18_0', 'num_var18', 'num_var20_0', 'num_var20', 'num_var24_0', 'num_var24', 'num_var26_0', 'num_var26', 'num_var25_0', 'num_var25', 'num_op_var40_hace2', 'num_op_var40_hace3', 'num_op_var40_ult1', 'num_op_var40_ult3', 'num_op_var41_hace2', 'num_op_var41_hace3', 'num_op_var41_ult1', 'num_op_var41_ult3', 'num_op_var39_hace2', 'num_op_var39_hace3', 'num_op_var39_ult1', 'num_op_var39_ult3', 'num_var27_0', 'num_var28_0', 'num_var28', 'num_var27', 'num_var29_0', 'num_var29', 'num_var30_0', 'num_var30', 'num_var31_0', 'num_var31', 'num_var32_0', 'num_var32', 'num_var33_0', 'num_var33', 'num_var34_0', 'num_var34', 'num_var35', 'num_var37_med_ult2', 'num_var37_0', 'num_var37', 'num_var39_0', 'num_var40_0', 'num_var40', 'num_var41_0', 'num_var41', 'num_var39', 'num_var42_0', 'num_var42', 'num_var44_0', 'num_var44', 'num_var46_0', 'num_var46', 'saldo_var1', 'saldo_var5', 'saldo_var6', 'saldo_var8', 'saldo_var12', 'saldo_var13_corto', 'saldo_var13_largo', 'saldo_var13_medio', 'saldo_var13', 'saldo_var14', 'saldo_var17', 'saldo_var18', 'saldo_var20', 'saldo_var24', 'saldo_var26', 'saldo_var25', 'saldo_var28', 'saldo_var27', 'saldo_var29', 'saldo_var30', 'saldo_var31', 'saldo_var32', 'saldo_var33', 'saldo_var34', 'saldo_var37', 'saldo_var40', 'saldo_var41', 'saldo_var42', 'saldo_var44', 'saldo_var46', 'var36', 'delta_imp_amort_var18_1y3', 'delta_imp_amort_var34_1y3', 'delta_imp_aport_var13_1y3', 'delta_imp_aport_var17_1y3', 'delta_imp_aport_var33_1y3', 'delta_imp_compra_var44_1y3', 'delta_imp_reemb_var13_1y3', 'delta_imp_reemb_var17_1y3', 'delta_imp_reemb_var33_1y3', 'delta_imp_trasp_var17_in_1y3', 'delta_imp_trasp_var17_out_1y3', 'delta_imp_trasp_var33_in_1y3', 'delta_imp_trasp_var33_out_1y3', 'delta_imp_venta_var44_1y3', 'delta_num_aport_var13_1y3', 'delta_num_aport_var17_1y3', 'delta_num_aport_var33_1y3', 'delta_num_compra_var44_1y3', 'delta_num_reemb_var13_1y3', 'delta_num_reemb_var17_1y3', 'delta_num_reemb_var33_1y3', 'delta_num_trasp_var17_in_1y3', 'delta_num_trasp_var17_out_1y3', 'delta_num_trasp_var33_in_1y3', 'delta_num_trasp_var33_out_1y3', 'delta_num_venta_var44_1y3', 'imp_amort_var18_hace3', 'imp_amort_var18_ult1', 'imp_amort_var34_hace3', 'imp_amort_var34_ult1', 'imp_aport_var13_hace3', 'imp_aport_var13_ult1', 'imp_aport_var17_hace3', 'imp_aport_var17_ult1', 'imp_aport_var33_hace3', 'imp_aport_var33_ult1', 'imp_var7_emit_ult1', 'imp_var7_recib_ult1', 'imp_compra_var44_hace3', 'imp_compra_var44_ult1', 'imp_reemb_var13_hace3', 'imp_reemb_var13_ult1', 'imp_reemb_var17_hace3', 'imp_reemb_var17_ult1', 'imp_reemb_var33_hace3', 'imp_reemb_var33_ult1', 'imp_var43_emit_ult1', 'imp_trans_var37_ult1', 'imp_trasp_var17_in_hace3', 'imp_trasp_var17_in_ult1', 'imp_trasp_var17_out_hace3', 'imp_trasp_var17_out_ult1', 'imp_trasp_var33_in_hace3', 'imp_trasp_var33_in_ult1', 'imp_trasp_var33_out_hace3', 'imp_trasp_var33_out_ult1', 'imp_venta_var44_hace3', 'imp_venta_var44_ult1', 'ind_var7_emit_ult1', 'ind_var7_recib_ult1', 'ind_var10_ult1', 'ind_var10cte_ult1', 'ind_var9_cte_ult1', 'ind_var9_ult1', 'ind_var43_emit_ult1', 'ind_var43_recib_ult1', 'var21', 'num_var2_0_ult1', 'num_var2_ult1', 'num_aport_var13_hace3', 'num_aport_var13_ult1', 'num_aport_var17_hace3', 'num_aport_var17_ult1', 'num_aport_var33_hace3', 'num_aport_var33_ult1', 'num_var7_emit_ult1', 'num_var7_recib_ult1', 'num_compra_var44_hace3', 'num_compra_var44_ult1', 'num_ent_var16_ult1', 'num_var22_hace2', 'num_var22_hace3', 'num_var22_ult1', 'num_var22_ult3', 'num_med_var22_ult3', 'num_med_var45_ult3', 'num_meses_var5_ult3', 'num_meses_var8_ult3', 'num_meses_var12_ult3', 'num_meses_var13_corto_ult3', 'num_meses_var13_largo_ult3', 'num_meses_var13_medio_ult3', 'num_meses_var17_ult3', 'num_meses_var29_ult3', 'num_meses_var33_ult3', 'num_meses_var39_vig_ult3', 'num_meses_var44_ult3', 'num_op_var39_comer_ult1', 'num_op_var39_comer_ult3', 'num_op_var40_comer_ult1', 'num_op_var40_comer_ult3', 'num_op_var40_efect_ult1', 'num_op_var40_efect_ult3', 'num_op_var41_comer_ult1', 'num_op_var41_comer_ult3', 'num_op_var41_efect_ult1', 'num_op_var41_efect_ult3', 'num_op_var39_efect_ult1', 'num_op_var39_efect_ult3', 'num_reemb_var13_hace3', 'num_reemb_var13_ult1', 'num_reemb_var17_hace3', 'num_reemb_var17_ult1', 'num_reemb_var33_hace3', 'num_reemb_var33_ult1', 'num_sal_var16_ult1', 'num_var43_emit_ult1', 'num_var43_recib_ult1', 'num_trasp_var11_ult1', 'num_trasp_var17_in_hace3', 'num_trasp_var17_in_ult1', 'num_trasp_var17_out_hace3', 'num_trasp_var17_out_ult1', 'num_trasp_var33_in_hace3', 'num_trasp_var33_in_ult1', 'num_trasp_var33_out_hace3', 'num_trasp_var33_out_ult1', 'num_venta_var44_hace3', 'num_venta_var44_ult1', 'num_var45_hace2', 'num_var45_hace3', 'num_var45_ult1', 'num_var45_ult3', 'saldo_var2_ult1', 'saldo_medio_var5_hace2', 'saldo_medio_var5_hace3', 'saldo_medio_var5_ult1', 'saldo_medio_var5_ult3', 'saldo_medio_var8_hace2', 'saldo_medio_var8_hace3', 'saldo_medio_var8_ult1', 'saldo_medio_var8_ult3', 'saldo_medio_var12_hace2', 'saldo_medio_var12_hace3', 'saldo_medio_var12_ult1', 'saldo_medio_var12_ult3', 'saldo_medio_var13_corto_hace2', 'saldo_medio_var13_corto_hace3', 'saldo_medio_var13_corto_ult1', 'saldo_medio_var13_corto_ult3', 'saldo_medio_var13_largo_hace2', 'saldo_medio_var13_largo_hace3', 'saldo_medio_var13_largo_ult1', 'saldo_medio_var13_largo_ult3', 'saldo_medio_var13_medio_hace2', 'saldo_medio_var13_medio_hace3', 'saldo_medio_var13_medio_ult1', 'saldo_medio_var13_medio_ult3', 'saldo_medio_var17_hace2', 'saldo_medio_var17_hace3', 'saldo_medio_var17_ult1', 'saldo_medio_var17_ult3', 'saldo_medio_var29_hace2', 'saldo_medio_var29_hace3', 'saldo_medio_var29_ult1', 'saldo_medio_var29_ult3', 'saldo_medio_var33_hace2', 'saldo_medio_var33_hace3', 'saldo_medio_var33_ult1', 'saldo_medio_var33_ult3', 'saldo_medio_var44_hace2', 'saldo_medio_var44_hace3', 'saldo_medio_var44_ult1', 'saldo_medio_var44_ult3', 'var38', 'TARGET']

Data types:
int64      265
float64    106
Name: count, dtype: int64

First five rows:

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0.0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0.0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0.0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0.0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0.0

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40296 entries, 0 to 40295
Columns: 371 entries, ID to TARGET
dtypes: float64(106), int64(265)
memory usage: 114.1 MB

In [3]:

missing = df.isnull().sum()

print("Total missing values:", missing.sum())

print("\nColumns containing missing values:")
print(missing[missing > 0])

Total missing values: 1

Columns containing missing values:
TARGET    1
dtype: int64

In [4]:

numeric_cols = df.select_dtypes(include=np.number).columns

df[numeric_cols] = df[numeric_cols].fillna(
    df[numeric_cols].median()
)

print("Missing values after cleaning:",
      df.isnull().sum().sum())

Missing values after cleaning: 0

In [5]:

print("Duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates().copy()

print("Shape after removing duplicate rows:", df.shape)

Duplicate rows: 0
Shape after removing duplicate rows: (40296, 371)

In [6]:

constant_cols = [
    col for col in df.columns
    if col != 'TARGET' and df[col].nunique(dropna=False) <= 1
]

print("Number of constant columns:", len(constant_cols))
print("Constant column names:", constant_cols)

df = df.drop(columns=constant_cols)

print("Shape after removing constant columns:", df.shape)

Number of constant columns: 50
Constant column names: ['ind_var2_0', 'ind_var2', 'ind_var18_0', 'ind_var18', 'ind_var27_0', 'ind_var28_0', 'ind_var28', 'ind_var27', 'ind_var34_0', 'ind_var34', 'ind_var41', 'ind_var46_0', 'ind_var46', 'num_var18_0', 'num_var18', 'num_var27_0', 'num_var28_0', 'num_var28', 'num_var27', 'num_var34_0', 'num_var34', 'num_var41', 'num_var46_0', 'num_var46', 'saldo_var18', 'saldo_var28', 'saldo_var27', 'saldo_var34', 'saldo_var41', 'saldo_var46', 'delta_imp_amort_var18_1y3', 'delta_imp_amort_var34_1y3', 'imp_amort_var18_hace3', 'imp_amort_var18_ult1', 'imp_amort_var34_hace3', 'imp_amort_var34_ult1', 'imp_reemb_var13_hace3', 'imp_reemb_var17_hace3', 'imp_reemb_var33_hace3', 'imp_trasp_var17_out_hace3', 'imp_trasp_var33_out_hace3', 'num_var2_0_ult1', 'num_var2_ult1', 'num_reemb_var13_hace3', 'num_reemb_var17_hace3', 'num_reemb_var33_hace3', 'num_trasp_var17_out_hace3', 'num_trasp_var33_out_hace3', 'saldo_var2_ult1', 'saldo_medio_var13_medio_hace3']
Shape after removing constant columns: (40296, 321)

In [7]:

feature_cols = [
    col for col in df.columns if col != 'TARGET'
]

duplicate_cols = df[feature_cols].T.duplicated()
duplicate_cols = duplicate_cols[duplicate_cols].index.tolist()

print("Number of duplicate feature columns:",
      len(duplicate_cols))
print("Duplicate columns:", duplicate_cols)

df = df.drop(columns=duplicate_cols)

print("Shape after removing duplicate columns:", df.shape)

Number of duplicate feature columns: 30
Duplicate columns: ['ind_var13_medio', 'ind_var26', 'ind_var25', 'ind_var29_0', 'ind_var29', 'ind_var32', 'ind_var37', 'ind_var40_0', 'ind_var40', 'ind_var39', 'num_var13_medio', 'num_var26', 'num_var25', 'num_var29_0', 'num_var29', 'num_var32', 'num_var37', 'num_var40_0', 'num_var40', 'num_var39', 'saldo_var29', 'saldo_var40', 'delta_num_reemb_var13_1y3', 'delta_num_reemb_var17_1y3', 'delta_num_reemb_var33_1y3', 'delta_num_trasp_var17_in_1y3', 'delta_num_trasp_var17_out_1y3', 'delta_num_trasp_var33_in_1y3', 'delta_num_trasp_var33_out_1y3', 'saldo_medio_var13_medio_ult1']
Shape after removing duplicate columns: (40296, 291)

In [8]:

print("Summary of numerical features:")
display(df.describe().T)

print("\nNumber of unique values per column:")
print(df.nunique().sort_values().head(20))

if 'var3' in df.columns:
    print("\nMost frequent values in var3:")
    print(df['var3'].value_counts().head(10))

Summary of numerical features:

,count,mean,std,min,25%,50%,75%,max
ID,40296.0,40331.641453,23245.994495,1.0,20212.7500,40368.50,60410.2500,80608.00
var3,40296.0,-1535.888004,39195.541222,-999999.0,2.0000,2.00,2.0000,235.00
var15,40296.0,33.222230,12.970947,5.0,23.0000,27.00,40.0000,102.00
imp_ent_var16_ult1,40296.0,90.993209,1842.526766,0.0,0.0000,0.00,0.0000,210000.00
imp_op_var39_comer_ult1,40296.0,72.766562,343.277922,0.0,0.0000,0.00,0.0000,12888.03
...,...,...,...,...,...,...,...,...
saldo_medio_var44_hace3,40296.0,2.326425,151.974893,0.0,0.0000,0.00,0.0000,18928.59
saldo_medio_var44_ult1,40296.0,84.964900,4480.561457,0.0,0.0000,0.00,0.0000,681462.90
saldo_medio_var44_ult3,40296.0,59.601170,2752.754696,0.0,0.0000,0.00,0.0000,374947.53
var38,40296.0,118604.114333,221951.317808,20.0,67838.0475,106587.72,119373.0225,22034738.76
TARGET,40296.0,0.038813,0.193151,0.0,0.0000,0.00,0.0000,1.00

Number of unique values per column:
TARGET                           2
ind_var1_0                       2
ind_var1                         2
ind_var5_0                       2
ind_var5                         2
ind_var6_0                       2
ind_var6                         2
ind_var8_0                       2
ind_var8                         2
ind_var12_0                      2
ind_var12                        2
ind_var13_0                      2
ind_var13_corto_0                2
ind_var13_corto                  2
saldo_medio_var13_medio_hace2    2
saldo_medio_var13_medio_ult3     2
num_trasp_var17_out_ult1         2
num_trasp_var33_in_hace3         2
num_trasp_var33_out_ult1         2
num_venta_var44_hace3            2
dtype: int64

Most frequent values in var3:
var3
 2         39333
 8            68
-999999       62
 3            60
 9            54
 1            50
 4            50
 13           47
 7            45
 6            44
Name: count, dtype: int64

In [9]:
print("Columns with only 1 unique value:")
print(df.columns[df.nunique() <= 1].tolist())

Columns with only 1 unique value:
[]

In [10]:
df['var3'] = df['var3'].replace(-999999, np.nan)

median_var3 = df['var3'].median()

df['var3'] = df['var3'].fillna(median_var3)

print("Remaining missing values:", df.isnull().sum().sum())
print("var3 median used:", median_var3)

Remaining missing values: 0
var3 median used: 2.0

In [11]:
print("Final dataset shape:", df.shape)

print("Remaining constant columns:",
      df.columns[df.nunique() <= 1].tolist())

print("Duplicate rows:", df.duplicated().sum())

Final dataset shape: (40296, 291)
Remaining constant columns: []
Duplicate rows: 0

In [12]:
# Separate features and target
X = df.drop(columns=['TARGET', 'ID'])
y = df['TARGET']

print("Features shape:", X.shape)
print("Target shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts())

Features shape: (40296, 289)
Target shape: (40296,)

Target distribution:
TARGET
0.0    38732
1.0     1564
Name: count, dtype: int64

In [17]:
train_clean = X_train.copy()
train_clean['TARGET'] = y_train

# Combine testing features and labels
test_clean = X_test.copy()
test_clean['TARGET'] = y_test

# Save the files
df.to_csv('/content/santander_cleaned.csv', index=False)

train_clean.to_csv(
    '/content/santander_train_clean.csv', index=False
)

test_clean.to_csv(
    '/content/santander_test_clean.csv', index=False
)

print("All cleaned files saved successfully!")

All cleaned files saved successfully!

In [19]:
import pandas as pd

raw_df = pd.read_csv('/content/train.csv')

print("Original dataset shape:", raw_df.shape)
print("Cleaned dataset shape:", df.shape)

Original dataset shape: (76020, 371)
Cleaned dataset shape: (40296, 291)

In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/train.csv')

print("Dataset restored:", df.shape)

Dataset restored: (76020, 371)

In [21]:
# Handle the special value in var3
df['var3'] = df['var3'].replace(-999999, np.nan)
df['var3'] = df['var3'].fillna(df['var3'].median())

# Fill any remaining missing numeric values
numeric_cols = df.select_dtypes(include=np.number).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

print("Missing values remaining:", df.isnull().sum().sum())
print("Dataset shape:", df.shape)

Missing values remaining: 0
Dataset shape: (76020, 371)

In [22]:
constant_cols = [
    col for col in df.columns
    if df[col].nunique() <= 1
]

print("Constant columns found:", len(constant_cols))

df = df.drop(columns=constant_cols)

print("Shape after removing constant columns:", df.shape)
print("Rows preserved:", len(df))

Constant columns found: 34
Shape after removing constant columns: (76020, 337)
Rows preserved: 76020

In [23]:
feature_cols = [col for col in df.columns if col != 'TARGET']

duplicate_cols = df[feature_cols].T.duplicated()
duplicate_cols = duplicate_cols[duplicate_cols].index.tolist()

print("Duplicate feature columns found:", len(duplicate_cols))

df = df.drop(columns=duplicate_cols)

print("Shape after removing duplicate columns:", df.shape)
print("Rows preserved:", len(df))

Duplicate feature columns found: 29
Shape after removing duplicate columns: (76020, 308)
Rows preserved: 76020

In [24]:
print("Duplicate rows:", df.duplicated().sum())
print("Final dataset shape:", df.shape)

Duplicate rows: 0
Final dataset shape: (76020, 308)

In [25]:
df.to_csv('/content/santander_cleaned.csv', index=False)

from google.colab import files
files.download('/content/santander_cleaned.csv')